### ISSUE TITLE
I'm getting the "Whoops, looks like something went wrong." error when trying to login?

### ISSUE THREAD

**Issue by LC3DPS** [gough/qmem#13]
I'm getting the "Whoops, looks like something went wrong." error when trying to login?

It happened right after deleting a user and then adding another new one.

**Comment by annikajn** [comment]
Hi Jeremy,

Are you still having the same problem? Is any of your other users having that problem?

Annika

**Comment by LC3DPS** [comment]
Yes,

All users were experiencing same issue.

I will check tomorrow and get back to you but it may have fixed itself. Lol Maybe something was reset on the backend. 

Thanks so much for responding back it’s greatly appreciated.

Jeremy

**Comment by LC3DPS** [comment]
@annikajn 

Hey,  Everything is up and running again. I'm not sure what caused it or how it fixed itself. Maybe something was happening with the server or some other network issue around campus. 

Have a great one!

Your group was so awesome and we still love the software system. 

Thanks again.

Jeremy
